const products = [{
    title: "Smart Fitness Watch",
    price: 249.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143299/smart-fitness-watch-jfrqIkFjNxfMz2FpRB5htLYKHhw8kY_jggtue.jpg",
    description: "Meet your ultimate wellness companion, the Smart Fitness Watch. Engineered for a modern, active lifestyle, this sleek wearable is more than a timepiece; it's your personal health coach. It tracks daily activities like steps, calories, and distance with precision. The advanced heart rate monitor and integrated GPS help optimize your workouts, from running to yoga. Stay seamlessly connected with notifications for calls, texts, and apps right on your wrist. Control your music, check the weather, and analyze your sleep patterns for a more restful night. With a long-lasting battery, customizable faces, and a water-resistant design, it’s ready for any adventure.",
    rating: 5.0,
    reviews: [],
    createdAt: new Date("2025-10-15"),
  },
  {
    title: "Wireless Earbuds Pro",
    price: 179.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143517/wireless-earbuds-pro-oKPqM9oN60Lib7jpOe92GqxI5egWdH_bv9q4z.jpg",
    description: "Immerse yourself in pure, uninterrupted sound with the Wireless Earbuds Pro. These earbuds deliver a superior audio experience with advanced active noise cancellation, blocking out distractions for crystal-clear music and calls. When you need to be aware, Transparency Mode lets you hear the world around you. Designed for a secure and comfortable fit with soft silicone tips, they are also sweat and water-resistant, perfect for workouts. Intuitive touch controls manage your audio effortlessly. Enjoy hours of listening time, extended by the compact wireless charging case, for a truly wireless and exceptional audio experience anywhere you go.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-10-14"),
  },
  {
    title: "4K Webcam",
    price: 129.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143706/4k-webcam-E8uStGVcj7MGvaxdhxiLyFdYaPgIwh_hexgty.jpg",
    description: "Elevate your video calls and content creation with our professional 4K Webcam. Delivering stunning, ultra-high-definition video, it captures every detail with exceptional clarity. The premium glass lens, intelligent autofocus, and automatic low-light correction ensure you look your best in any environment. Dual omni-directional microphones with noise-cancellation provide crystal-clear audio by filtering out background noise. With a wide 90-degree field of view, plug-and-play USB connectivity, and a versatile mounting clip, setup is effortless. An integrated privacy shutter gives you complete control and peace of mind. Make a lasting impression in every meeting and stream.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-10-13"),
  },
  {
    title: "USB-C Hub",
    price: 49.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143863/usb-c-hub-kIWXrZ0JSjlIIic9AaQqPXB3pFFAzb_kwvaqu.jpg",
    description: "Unlock your device's full potential with our versatile USB-C Hub. This compact, all-in-one solution transforms a single USB-C port into a powerhouse of productivity. It features a 4K HDMI port for screen mirroring, multiple high-speed USB 3.0 ports for fast data transfer, and integrated SD/microSD card readers. The 100W Power Delivery port allows you to charge your laptop while using all other functions. Crafted from durable aluminum for excellent heat dissipation, its slim, lightweight design is perfect for on-the-go productivity. Plug-and-play functionality ensures instant use with a wide range of USB-C devices.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-10-12"),
  },
  {
    title: "Mechanical Keyboard",
    price: 159.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143906/mechanical-keyboard-IXU7mTfsOdw9FvR7Fh3qpQULw0AP7R_adzvns.jpg",
    description: "Elevate your typing and gaming with our premium Mechanical Keyboard. Engineered for performance and durability, it features high-quality mechanical switches for satisfying tactile feedback and precision. With full N-key rollover and anti-ghosting, every keystroke is registered, giving you a competitive edge. The customizable RGB backlighting offers over 16.8 million colors for an immersive setup. Built with a solid aluminum frame and wear-resistant PBT keycaps, this keyboard is made to last. The ergonomic design, including a detachable wrist rest, ensures comfort during long sessions. It's the ultimate tool for programmers, writers, and gamers seeking excellence.",
    rating: 4.9,
    reviews: [],
    createdAt: new Date("2025-10-11"),
  },
  {
    title: "Wireless Mouse",
    price: 39.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143952/wireless-mouse-gaYSdYszQdxE3riM1dHTIR8Wg8mVLS_hdbdbk.jpg",
    description: "Experience freedom and precision with our high-performance Wireless Mouse. Designed for comfort and reliability, its advanced optical sensor provides smooth, accurate tracking with adjustable DPI for customized control. The ergonomic shape reduces hand strain, while silent-click buttons ensure a quiet, distraction-free environment. Enjoy a stable, lag-free connection with the 2.4GHz wireless technology and a plug-and-play nano receiver. Intelligent power-saving features extend battery life for months. Compatible with all major operating systems, this lightweight and portable mouse is the perfect accessory for a clutter-free and productive workspace, wherever you are.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-10-10"),
  },
  {
    title: "Portable SSD 1TB",
    price: 99.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144000/portable-ssd-1tb-0d5ECzoXdqA5M7WZkDeBTCVOLopEKQ_iix9fx.jpg",
    description: "Experience lightning-fast data transfer with our Portable SSD 1TB. This compact and powerful drive is the ultimate solution for professionals and content creators. With read/write speeds up to 1,050MB/s, you can transfer 4K videos and large files in seconds. The 1TB capacity provides ample space for your digital world. Its durable, shock-resistant design protects your data from drops, while AES 256-bit hardware encryption ensures security. Compatible with a wide range of devices, its palm-sized form factor makes it incredibly portable. Get the perfect blend of speed, durability, and security for your on-the-go storage needs.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-10-09"),
  },
  {
    title: "Laptop Stand",
    price: 29.99,
    category: "Electronics",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/laptop-stand-UZwVML7JKLStw6NPbvydtfVzegEagp.jpg",
    description: "Improve your comfort and productivity with our ergonomic Laptop Stand. Designed to elevate your laptop to the perfect eye level, it reduces neck and back strain by promoting better posture. Crafted from sturdy, lightweight aluminum, its open design enhances airflow to prevent overheating. The adjustable height and angle settings allow you to create a customized workstation anywhere. Non-slip silicone pads keep your laptop secure and protect your surfaces. Compatible with a wide range of laptops, this stand folds flat for easy portability. It's an essential tool for a healthier and more efficient work environment.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-10-08"),
  },
  {
    title: "Portable Charger 20000mAh",
    price: 34.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144093/portable-charger-20000mah-YNA4lKuklHzgOUpMny2vsky8HiA8cK_vtivcu.jpg",
    description: "Stay powered up on the go with our high-capacity 20000mAh Portable Charger. This reliable power bank can charge most smartphones multiple times, making it perfect for travel, long days, or emergencies. Equipped with multiple USB-A and USB-C ports, it supports fast charging for up to three devices simultaneously. The smart charging technology ensures safe and efficient power delivery, while the clear LED display shows the remaining battery life. Its slim, lightweight design and durable finish make it easy to carry. With a comprehensive multi-protection system, this portable charger is an essential accessory for modern life.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-10-07"),
  },
  {
    title: "Bluetooth Speaker",
    price: 79.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144146/bluetooth-speaker-fkonqloSW5rgNnI42W53u864qTmlZO_hmlpet.jpg",
    description: "Bring your music to life with our powerful and portable Bluetooth Speaker. It delivers an immersive audio experience with rich, 360-degree sound, deep bass, and crisp highs. The latest Bluetooth 5.0 technology ensures a fast, stable connection up to 30 meters. Built for adventure, this speaker is rugged and IPX7 waterproof, making it perfect for the beach, pool, or hiking. The long-lasting battery provides up to 12 hours of playtime. A built-in microphone allows for clear, hands-free calls. Compact, lightweight, and with a convenient strap, it's the perfect companion for any musical journey.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-10-06"),
  },
  {
    title: "Wireless Charger",
    price: 24.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144180/wireless-charger-cAhfJTX7WE8xIXDsj05hvZ2eOgrLG9_dtcqbm.jpg",
    description: "Simplify your charging routine with our sleek and efficient Wireless Charger. This pad offers a convenient, cable-free way to power up your Qi-enabled devices. Just place your smartphone or earbuds on the pad for instant charging. It supports up to 15W fast wireless charging and features an intelligent system that protects against overheating and overcharging. The slim, minimalist design with a non-slip surface complements any space. It's case-friendly and universally compatible with all Qi-certified devices. Say goodbye to tangled cables and enjoy the ease of drop-and-go charging for your home or office.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-10-05"),
  },
  {
    title: "USB-C Cable 3-Pack",
    price: 19.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144217/usb-c-cable-3pack-sqWWYTQFRGFhRSCISUWoveSGBfBbXc_vxkuxd.jpg",
    description: "Stay connected with our durable and versatile USB-C Cable 3-Pack. This pack includes three high-quality, braided nylon cables in varying lengths (3ft, 6ft, 10ft) to meet all your charging and data transfer needs. Built to last, they resist tangling and fraying. These cables support fast charging up to 60W and high-speed data transfer up to 480Mbps, perfect for smartphones, tablets, and laptops. The reversible USB-C connector ensures easy use every time. Compatible with a wide range of devices, this 3-pack offers exceptional value and convenience for home, office, or travel.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-10-04"),
  },
  {
    title: "Screen Protector Pack",
    price: 14.99,
    category: "Electronics",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/screen-protector-pack-TkpNIqaZCLk7FtwlcwAqXbfDmwsvzY.jpg",
    description: "Protect your device's screen with our premium Screen Protector Pack. This pack includes multiple high-quality tempered glass protectors, offering superior defense against scratches, scuffs, and impacts. Crafted from 9H hardness tempered glass, it provides maximum durability while maintaining original screen brightness and clarity. The oleophobic coating repels fingerprints and smudges. With a precise, laser-cut design and an included alignment frame, installation is bubble-free and effortless. The ultra-thin profile ensures full touch sensitivity and case compatibility. Safeguard your investment and keep your screen looking flawless with this essential, cost-effective protection solution.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-10-03"),
  },
  {
    title: "Phone Case",
    price: 19.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144286/phone-case-NvZDfGEWqmXg8F1RNsk29yCd0Qcrkd_qn5jvs.jpg",
    description: "Safeguard your smartphone with our stylish and durable Phone Case. It offers the perfect balance of protection and aesthetics, crafted from a shock-absorbent TPU bumper and a scratch-resistant polycarbonate back. Raised bezels protect the screen and camera from scratches. The slim, lightweight design preserves your phone's sleek profile while providing a secure, non-slip grip. Precise cutouts ensure easy access to all ports and buttons. The crystal-clear, anti-yellowing back showcases your phone's original design. Compatible with wireless charging, this case offers robust protection without sacrificing convenience or style. Protect your investment with this essential accessory.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-10-02"),
  },
  {
    title: "Tablet Stand",
    price: 22.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144330/tablet-stand-kO5tR2A8FeKj2pxRhaoa5sliOPz5m6_z8yvlx.jpg",
    description: "Enhance your tablet experience with our versatile and sturdy Tablet Stand. It provides a comfortable, hands-free viewing experience, perfect for watching movies, video calls, or following recipes. The adjustable design helps you find the perfect angle, reducing neck strain and promoting better posture. Crafted from premium aluminum, it's both lightweight and durable. Non-slip silicone pads keep your device secure and scratch-free. Compatible with a wide range of tablets, its foldable design makes it compact and portable. This stand is an essential accessory for a more comfortable and productive digital life at home or on the go.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-10-01"),
  },
  {
    title: "HDMI Cable 2-Pack",
    price: 16.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144513/61JL7RYC18L._UF1000_1000_QL80__bfczs6.jpg",
    description: "Ensure a high-quality, reliable connection for your home entertainment with our HDMI Cable 2-Pack. These premium, high-speed cables support 4K Ultra HD video at 60Hz and HDR, delivering stunning colors and incredible detail for movies, gaming, and streaming. They also support immersive audio formats like Dolby TrueHD. Built to last with a durable braided nylon jacket and gold-plated connectors, these cables resist fraying and corrosion. This convenient 2-pack allows you to connect multiple devices, such as Blu-ray players, gaming consoles, and laptops, to your TV or monitor. Enjoy a flawless entertainment experience.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-09-30"),
  },
  {
    title: "Monitor Light Bar",
    price: 89.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144732/Pura_Monitor_Light_Bar_7_1024x1024_jxsahq.jpg",
    description: "Transform your workspace and reduce eye strain with our innovative Monitor Light Bar. This sleek lighting solution mounts on top of your monitor, saving desk space and illuminating your workspace without causing screen glare. The asymmetrical design reduces eye fatigue during long hours of computer use. Customize your lighting with adjustable brightness and color temperature settings, from warm to cool, via simple touch controls. Powered by USB-C, it offers a clutter-free setup. The flicker-free LED lights provide natural, even illumination, improving your visual comfort and focus. It's an essential tool for a more productive work environment.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-29"),
  },
  {
    title: "Webcam Ring Light",
    price: 34.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/c_crop,w_1024,h_1024/v1761144801/RingLight18_01_gzj9zb.jpg",
    description: "Achieve professional-quality lighting for your video calls and streams with our versatile Webcam Ring Light. This compact light clips directly onto your laptop, monitor, or smartphone, providing soft, even, and flattering illumination. Customize your look with adjustable brightness and three color modes (warm, cool, neutral) to match any environment. The diffused light eliminates harsh shadows and creates a beautiful catchlight in your eyes for a polished appearance. Powered by USB, its lightweight design makes it perfect for on-the-go use. It's an essential, affordable tool for a flawless on-camera presence.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-28"),
  },
  {
    title: "Desk Lamp",
    price: 44.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144903/executivetablelamp_b1j31a.jpg",
    description: "Illuminate your workspace with our modern and elegant Desk Lamp. It provides optimal, adjustable lighting for reading, working, or studying. With a flexible arm and rotating head, you can direct light exactly where you need it. Customize your lighting with multiple brightness levels and color temperature modes using simple touch controls. The energy-efficient, flicker-free LED light reduces eye strain. This lamp also includes a convenient built-in USB charging port to keep your devices powered. Its sleek, minimalist design and sturdy base make it a stylish and functional addition to any home or office.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-27"),
  },
  {
    title: "Cable Organizer",
    price: 12.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144970/realike-travel-cable-organizer-electronic-accessories-organizer-for-cord-hard-drive-earphone-power-bank-and-others-13469066461284_1024x1024_isxeox.jpg",
    description: "Tame the tangle of cables with our practical and stylish Cable Organizer. This compact organizer is the perfect solution for managing your charging cables, adapters, and earbuds at home or on the go. It features multiple elastic loops and mesh pockets to keep your accessories secure and easy to find. The durable, water-resistant exterior and padded interior protect your items from damage. Its slim, lightweight design fits easily into any bag, making it an essential travel companion. Say goodbye to cable clutter and hello to a more organized and efficient way of managing your electronics.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-09-26"),
  },
  {
    title: "Classic White T-Shirt",
    price: 29.99,
    category: "Fashion & Apparel",
    image: "https://cdn.thewirecutter.com/wp-content/media/2025/09/BEST-MENS-WHITE-TEES-SUB-2048px-5935.jpg?auto=webp&quality=75&width=1024",
    description: "Elevate your wardrobe with our Classic White T-Shirt, a timeless staple combining comfort and style. Crafted from 100% premium, long-staple cotton, it offers a soft, breathable feel. The fabric is pre-shrunk for a consistent fit, wash after wash. With a classic crewneck and modern tailored fit, it's a versatile piece for any occasion, perfect on its own or for layering. Reinforced stitching ensures durability, while the tag-free neck provides added comfort. This t-shirt is the ultimate foundation for any outfit, offering a clean, simple design that pairs effortlessly with anything in your closet.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-25"),
  },
  {
    title: "Blue Denim Jeans",
    price: 79.99,
    category: "Fashion & Apparel",
    image: "https://www.mumkins.in/cdn/shop/products/denim-jeans-for-kids-bl0612345-darkblue-1_1024x1024.jpg?v=1757575343",
    description: "Discover your new favorite pair of classic Blue Denim Jeans, a wardrobe essential offering the perfect blend of style, comfort, and durability. Crafted from high-quality denim with a hint of stretch, they provide a comfortable, flexible fit. The timeless blue wash, five-pocket design, and straight-leg cut create a flattering silhouette that never goes out of style. Reinforced stitching and durable hardware ensure these jeans are built to last. Subtle fading and whiskering add a touch of vintage character. Pair them with a t-shirt for a casual look or dress them up with a button-down shirt.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-24"),
  },
  {
    title: "Black Leather Jacket",
    price: 199.99,
    category: "Fashion & Apparel",
    image: "https://www.noorainternational.biz/cdn/shop/files/Myproject-1_5_1024x1024.jpg?v=1690871206",
    description: "Make a bold statement with our iconic Black Leather Jacket, a timeless piece that exudes confidence and style. Crafted from 100% genuine, full-grain leather, it offers a luxurious feel and exceptional durability that gets better with age. The classic biker-style design features an asymmetrical zipper, notched lapels, and multiple zippered pockets for an edgy, sophisticated look. A tailored fit and smooth satin lining ensure comfort and easy layering. This versatile jacket is perfect for any occasion, adding an instant dose of attitude to any outfit. It's more than a jacket; it's a symbol of timeless style.",
    rating: 4.9,
    reviews: [],
    createdAt: new Date("2025-09-23"),
  },
  {
    title: "Summer Dress",
    price: 59.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/summer-dress-0VJHv3JqYlEwT6PXd7dRGTRSSwS76Q.jpg",
    description: "Embrace the sunshine with our beautiful and breezy Summer Dress. Designed to keep you cool and stylish, it's crafted from a lightweight, breathable fabric that feels soft against your skin. The relaxed, flowy silhouette provides a flattering and comfortable fit for all body types. Featuring a vibrant print, a flattering neckline, and a practical knee-length hem, this dress is effortlessly chic. It's a versatile piece that can be dressed up or down for any occasion. Perfect for travel, it's easy to care for and resists wrinkling. Feel beautiful and confident all season long.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-22"),
  },
  {
    title: "Casual Hoodie",
    price: 49.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/casual-hoodie-fy6hMYb29TrBfW8JAQiJWo4Oqjkril.jpg",
    description: "Stay cozy and stylish with our versatile Casual Hoodie, the ultimate comfort piece for your wardrobe. Crafted from a soft fleece fabric, it provides the perfect amount of warmth for cooler days. The relaxed fit, adjustable drawstring hood, and spacious kangaroo pocket make it a go-to choice for lounging or running errands. Ribbed cuffs and hem ensure a snug fit. With its minimalist design and high-quality construction, this hoodie is easy to pair with jeans or joggers. It's the perfect layering piece for any season, combining comfort, style, and practicality for your everyday life.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-21"),
  },
  {
    title: "Running Shoes",
    price: 119.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/running-shoes-g0gyL1uiU320toVAxbwRNu5R8zkxF0.jpg",
    description: "Unleash your potential with our high-performance Running Shoes, engineered for the perfect balance of comfort, support, and responsiveness. The lightweight, breathable mesh upper keeps your feet cool, while the seamless construction reduces irritation. Responsive midsole cushioning provides exceptional energy return, reducing impact on your joints. The durable rubber outsole offers excellent traction on various surfaces. A supportive heel counter and midfoot cage ensure a secure fit, preventing injury. With a sleek, modern design, these shoes are perfect for runners of all levels, helping you achieve your fitness goals with every step.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-20"),
  },
  {
    title: "Formal Blazer",
    price: 149.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/formal-blazer-EPJ8kUYTNiuDFfq0ayYQdfutrVSjsE.jpg",
    description: "Elevate your professional and formal attire with our impeccably tailored Formal Blazer. This sophisticated piece is a cornerstone of any polished wardrobe, exuding confidence and timeless style. Crafted from a premium wool-blend fabric, it offers a luxurious feel and a structured silhouette. The classic single-breasted design features a two-button closure and notched lapels. Expertly tailored for a flattering, modern fit, its clean lines create a sharp look perfect for business meetings or formal events. This versatile blazer pairs well with trousers or dark-wash jeans, making it a timeless investment in refined taste.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-19"),
  },
  {
    title: "Casual Sneakers",
    price: 89.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/casual-sneakers-qYGY9HdtSFR3cXHmOIIKx8PkChK2ER.jpg",
    description: "Step up your everyday style with our versatile and comfortable Casual Sneakers. They are the perfect combination of modern design and all-day comfort. The upper is crafted from premium leather and breathable canvas for a stylish, durable finish. A cushioned insole and padded collar provide exceptional comfort, while the durable rubber outsole offers excellent traction. The minimalist design and low-top silhouette create a timeless look that pairs effortlessly with jeans or chinos. These sneakers are a go-to choice for any casual occasion, blending style, comfort, and practicality into one essential piece of footwear.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-18"),
  },
  {
    title: "Wool Sweater",
    price: 69.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/wool-sweater-k7dNfTXsCdEguuRASAJ6JyQw0M4gws.jpg",
    description: "Embrace the warmth and timeless style of our classic Wool Sweater. Crafted from 100% pure, soft merino wool, it offers exceptional warmth, breathability, and a luxurious feel. The classic crewneck design and regular fit make it a versatile addition to any wardrobe. Ribbed collar, cuffs, and hem provide a snug, comfortable fit and help maintain the sweater's shape. This sweater is a versatile layering piece that can be dressed up with a collared shirt or down with jeans. It's an investment in timeless style, quality, and comfort, perfect for transitioning between seasons.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-17"),
  },
  {
    title: "Cargo Pants",
    price: 74.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/cargo-pants-S5UmJ6tvjRjysdJZvXg54ZEQ4FZw1c.jpg",
    description: "Combine rugged utility with modern style in our versatile Cargo Pants. Designed for adventure and everyday wear, they offer a perfect blend of functionality, comfort, and durability. Crafted from tough, breathable cotton twill, they feature a relaxed, straight-leg fit for ample movement. Multiple cargo pockets provide plenty of storage for your essentials. Reinforced stitching and an adjustable waistband ensure a secure, long-lasting fit. Pair them with hiking boots for an outdoor adventure or sneakers for a relaxed, everyday look. These pants are the perfect combination of rugged style and practical design, ready for anything.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-09-16"),
  },
  {
    title: "Polo Shirt",
    price: 44.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/polo-shirt-WChYflDB7ZTVwMa6FxOuKf8TZ4F00T.jpg",
    description: "Achieve effortless sophistication with our classic Polo Shirt. This timeless staple bridges the gap between casual and smart, making it a must-have for any wardrobe. Crafted from premium, breathable cotton pique, it provides all-day comfort and a polished appearance. The classic design features a two-button placket, a ribbed collar, and a regular fit that is both comfortable and flattering. Pair it with chinos for a smart-casual look or with shorts for a relaxed weekend ensemble. It's the perfect combination of comfort, quality, and timeless style, a symbol of refined, casual elegance.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-15"),
  },
  {
    title: "Leather Belt",
    price: 39.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/leather-belt-XqiNhkVB5r2LL29lGRnG14vWBu3lbd.jpg",
    description: "Complete your look with our classic and durable Leather Belt, an essential accessory for any wardrobe. Crafted from 100% genuine, full-grain leather, it offers a timeless look and exceptional durability that improves with age. The high-quality leather is both strong and supple, providing a comfortable, secure fit. The classic design features a polished, single-prong metal buckle, making it a versatile choice for both formal trousers and casual jeans. This belt is a statement of quality and classic style, the perfect finishing touch to any outfit, adding a touch of sophistication and refinement.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-14"),
  },
  {
    title: "Sunglasses",
    price: 99.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/sunglasses-V2Srj7WtRy7xjDv94mhk1wAQI47k6Q.jpg",
    description: "Protect your eyes and elevate your style with our classic and sophisticated Sunglasses. They provide superior protection with high-quality lenses offering 100% UV400 protection. The polarized lenses reduce glare from reflective surfaces, providing a clearer, more comfortable view. The frames are crafted from a lightweight, durable material for a comfortable and secure fit. With a timeless design that flatters a variety of face shapes, these sunglasses are a versatile accessory for any occasion. They are the perfect finishing touch to any outfit, adding a touch of cool, effortless style while protecting your eye health.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-13"),
  },
  {
    title: "Backpack",
    price: 79.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/backpack-T5L1l2mCl8tRSYRdojqa3JBdJZARZ5.jpg",
    description: "Carry your essentials in style and comfort with our versatile and durable Backpack. It's designed for students, professionals, and travelers, offering a perfect blend of functionality and modern design. Crafted from a high-quality, water-resistant material, it features a spacious main compartment, a padded laptop sleeve, and multiple pockets for organization. Ergonomic, padded shoulder straps and back panel provide exceptional comfort. The sleek, minimalist design is both stylish and professional, making it a great choice for any setting. With its durable construction and practical features, this backpack is ready for any adventure.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-12"),
  },
  {
    title: "Crossbody Bag",
    price: 59.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/crossbody-bag-R3IGMGYCwMxA8VtoqS6imHdAr9aV8m.jpg",
    description: "Travel light and stay organized with our stylish and practical Crossbody Bag. This compact bag is perfect for carrying your essentials without the bulk. Crafted from a durable, lightweight material, it features a spacious main compartment and multiple pockets for organization. The adjustable crossbody strap allows for a customized, comfortable fit. Secure zipper closures keep your belongings safe. With its sleek, minimalist design, it's a versatile accessory for any outfit. This bag is the perfect combination of style, comfort, and practicality, keeping your hands free and your essentials close at hand.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-11"),
  },
  {
    title: "Winter Coat",
    price: 179.99,
    category: "Fashion & Apparel",
    image: "https://affairweatherkennel.com/wp-content/uploads/2024/06/Men_s-Hooded-Winter-Coat-Puffer-Jacket-Thicken-Warm-Fur-Down-Parka-Jacket-with-Removable-Hood_4-1024x1024.jpg",
    description: "Brave the coldest days in style and comfort with our premium Winter Coat. Engineered for exceptional warmth and protection, it's an essential for any winter wardrobe. Crafted from a water-resistant and windproof outer shell, it features thick, high-loft insulation for superior warmth. The classic parka design includes a longer length, a full-zip front, and a cozy, faux-fur-trimmed hood. Multiple pockets and fleece-lined hand-warmer pockets provide ample storage and comfort. This coat is the perfect combination of style, warmth, and practicality, designed to keep you comfortable and protected all winter long.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-10"),
  },
  {
    title: "Shorts",
    price: 39.99,
    category: "Fashion & Apparel",
    image: "https://www.dukeindia.com/cdn/shop/files/5_03adfdfc-5669-41be-a4c5-e76024e3704d_1024x1024.jpg?v=1702463834",
    description: "Stay cool and comfortable in our classic and versatile Shorts. Designed for warm weather and active lifestyles, they offer a perfect blend of comfort, style, and practicality. Crafted from a lightweight, breathable cotton-blend fabric, they feature a classic flat-front design and a regular fit for a clean, timeless look. The knee-length inseam and four-pocket design provide a comfortable, modern fit with ample storage. These shorts are a versatile addition to any casual wardrobe, perfect for a day at the beach or a barbecue with friends. Stay cool and stylish all season long.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-09-09"),
  },
  {
    title: "Scarf",
    price: 29.99,
    category: "Fashion & Apparel",
    image: "https://www.annabeltrends.com/cdn/shop/products/63SSB_Slip_through_Scarf_Black_2.jpg?v=1683872166",
    description: "Add a touch of elegance and warmth to any outfit with our soft and stylish Scarf. This versatile accessory is perfect for completing your look, whether for a special occasion or a chilly day. Crafted from a high-quality, lightweight fabric, it feels incredibly soft and comfortable. The generous size allows for a variety of styling options. With its classic design, neutral color options, and subtle texture, it's a timeless accessory that can be paired with a wide range of outfits. This scarf is the perfect finishing touch to elevate your look and stay cozy.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-08"),
  },
  {
    title: "Watch",
    price: 149.99,
    category: "Fashion & Apparel",
    image: "https://m.media-amazon.com/images/I/61liwYpcANL._UY1000_.jpg",
    description: "Elevate your style with our classic and sophisticated Watch. This timeless timepiece is a perfect blend of traditional craftsmanship and modern design. It features a durable stainless steel case and a high-quality leather or stainless steel strap for a comfortable, secure fit. The classic analog display has a clean, easy-to-read dial with elegant hour markers. A scratch-resistant mineral crystal and reliable quartz movement ensure accurate timekeeping. This water-resistant watch is a versatile accessory for any outfit, from formal suits to casual wear. It's a statement of classic style and enduring quality.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-07"),
  },
  {
    title: "Gloves",
    price: 24.99,
    category: "Fashion & Apparel",
    image: "https://www.bestmarine.com/cdn/shop/files/PVCgloves_1024x1024.jpg?v=1744970541",
    description: "Keep your hands warm and protected with our classic and durable Gloves. Designed for both warmth and dexterity, they are a practical and stylish accessory for the colder months. Crafted from a high-quality material, such as soft leather or a warm wool-blend, they provide excellent insulation and a comfortable fit. The soft lining ensures a cozy feel. The timeless, versatile design is perfect for a variety of occasions. These gloves are the perfect combination of warmth, comfort, and style, an essential accessory for anyone who wants to stay warm and look good during the winter.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-09-06"),
  },
  {
    title: "Blender",
    price: 89.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/blender-epIlNICv0ESTjq0KtLAoPpYkOdYiu8.jpg",
    description: "Unleash your culinary creativity with our powerful and versatile Blender. This high-performance blender handles a wide range of tasks, from smoothies and soups to sauces and nut butters. The powerful motor and durable stainless steel blades effortlessly crush ice and create smooth, creamy textures. The large-capacity, BPA-free pitcher is perfect for family-sized batches. Variable speed control and a pulse function give you complete control over the consistency. The easy-to-clean design, including a self-cleaning function, makes cleanup a breeze. It's a versatile kitchen appliance that will inspire you to create delicious and healthy meals.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-05"),
  },
  {
    title: "Coffee Maker",
    price: 79.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/coffee-maker-R1K2m4nrNJHrzXdgbqzbuBaE3cl8Nb.jpg",
    description: "Start your day right with a perfect cup of coffee from our reliable and easy-to-use Coffee Maker. It's designed to brew delicious, aromatic coffee with the touch of a button. The programmable timer lets you wake up to the smell of freshly brewed coffee. The large-capacity, 12-cup carafe is perfect for families or guests. A brew-pause function lets you pour a cup mid-brew. The non-stick warming plate keeps your coffee hot, and the automatic shut-off provides peace of mind. With its sleek design, it's the perfect choice for any coffee lover.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-04"),
  },
  {
    title: "Cookware Set",
    price: 129.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/cookware-set-ugpyL0IK68PZTqjtE7hZvfBk12WMmg.jpg",
    description: "Equip your kitchen with our comprehensive and high-quality Cookware Set. It includes everything you need to create delicious meals. Each piece is crafted from a durable, heat-conductive material for even heat distribution. The non-stick coating makes cooking and cleanup a breeze, while tempered glass lids allow you to monitor your food. Comfortable, stay-cool handles provide a secure grip. This set includes a variety of pots and pans in different sizes, along with essential kitchen utensils. It's the perfect choice for anyone who loves to cook, from beginners to experienced chefs.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-03"),
  },
  {
    title: "Knife Set",
    price: 59.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/knife-set-yS7fJw5ilD9FMTQT4Gk3HlKBVD3m6Y.jpg",
    description: "Upgrade your culinary skills with our professional-quality Knife Set. This comprehensive set includes essential knives for all your food preparation needs. Each knife is forged from high-carbon stainless steel for a sharp, durable, and corrosion-resistant blade. The ergonomic, triple-riveted handles provide a comfortable, secure grip. The set includes a chef's knife, bread knife, slicing knife, utility knife, paring knife, and steak knives, all housed in a stylish wooden block. This knife set is an investment in your culinary passion, providing the right tool for every task and making food preparation easier and more enjoyable.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-02"),
  },
  {
    title: "Cutting Board",
    price: 24.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/cutting-board-YROhMrfOmieSuIkYZuoG3S2leovayf.jpg",
    description: "Prepare your meals with ease and style on our durable and versatile Cutting Board. This essential kitchen tool is crafted from a high-quality, non-porous material that is gentle on your knives and easy to clean. The generous size provides ample space for chopping, while the built-in juice groove keeps your countertop clean. Non-slip feet provide a stable cutting surface. The reversible design allows for separate use for meats and vegetables, preventing cross-contamination. This cutting board is a practical and stylish addition to any kitchen, essential for safe and efficient food preparation.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-01"),
  },
  {
    title: "Microwave",
    price: 99.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/modern-microwave-oven-XafSbb8a2ibnyNoVhRZC0fDPQkpo15.png",
    description: "Simplify your cooking and reheating with our modern and efficient Microwave. This powerful appliance saves you time and effort in the kitchen. The spacious interior and turntable ensure even cooking for a variety of dishes. Intuitive digital controls and pre-programmed settings make it easy to cook everything from popcorn to frozen dinners. The defrost function quickly thaws frozen foods. With its sleek design and easy-to-clean interior, this microwave is a reliable and convenient addition to any kitchen. It's a smart and stylish investment in your kitchen convenience, perfect for busy professionals, students, and parents.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-31"),
  },
  {
    title: "Toaster",
    price: 34.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/toaster-VNFMTCna5zSa6SDmgQytLP6ml8yd1m.jpg",
    description: "Start your day with perfectly toasted bread and bagels with our classic and reliable Toaster. It's designed for even, consistent toasting, with wide slots to accommodate a variety of bread sizes. The variable browning control lets you customize the toasting level to your preference. Cancel, defrost, and reheat functions provide added convenience. A high-lift lever makes it easy to remove smaller items, and the removable crumb tray ensures quick cleanup. With its sleek, compact design, this toaster is a reliable and affordable appliance that will become an essential part of your kitchen.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-08-30"),
  },
  {
    title: "Kettle",
    price: 29.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/electric-kettle-fIq5HXwjrz6TkX5SH040d51e7KntOJ.png",
    description: "Boil water quickly and efficiently with our stylish and convenient Kettle. This electric kettle is designed for speed and safety, with a powerful heating element that boils water in minutes. The large capacity is perfect for tea, coffee, or instant noodles. Automatic shut-off and boil-dry protection provide peace of mind. The cordless design and 360-degree swivel base make it easy to lift and pour. A water level indicator and removable filter add to its convenience. With its sleek, modern design, this kettle is a reliable and affordable appliance for any kitchen.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-29"),
  },
  {
    title: "Dish Set",
    price: 49.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/dish-set-efMZvCm21PpHXXJKATfzrJuYo6PgDL.jpg",
    description: "Set a beautiful table with our elegant and durable Dish Set. This comprehensive set includes everything you need for a complete dining experience, from dinner plates and salad plates to bowls and mugs. Each piece is crafted from high-quality, chip-resistant porcelain or stoneware for a durable, long-lasting design. The classic, timeless design is perfect for both everyday use and special occasions. The dishes are microwave and dishwasher-safe, making them easy to use and care for. This dish set is the perfect choice for creating a beautiful and inviting dining experience for your family and friends.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-28"),
  },
  {
    title: "Storage Containers",
    price: 39.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/storage-containers-ZaID6QrLug4FlyR6bc3B0nYFjK8j94.jpg",
    description: "Keep your kitchen organized and your food fresh with our versatile and practical Storage Containers. This set includes a variety of sizes, perfect for storing leftovers, snacks, and pantry staples. Each container is crafted from durable, BPA-free plastic. The airtight, leak-proof lids keep food fresh and prevent spills. The clear design allows you to easily see what's inside. These containers are stackable and nestable for easy storage, and they are microwave, freezer, and dishwasher-safe for ultimate convenience. It's a practical and affordable solution for a more organized kitchen.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-27"),
  },
  {
    title: "Vacuum Cleaner",
    price: 199.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/vacuum-cleaner-IKo5QHbtyX64j0TDE0dYJhohVUyPFv.jpg",
    description: "Keep your home clean and fresh with our powerful and efficient Vacuum Cleaner. It's designed to tackle dirt, dust, and debris on a variety of surfaces, from carpets to hardwood floors. The powerful motor and cyclonic suction provide a deep, thorough clean. Its lightweight, maneuverable design makes it easy to clean around furniture and in tight spaces. The large-capacity dustbin is easy to empty. This vacuum includes a variety of attachments to help you clean every nook and cranny. It's a reliable and affordable appliance that will make cleaning a breeze.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-08-26"),
  },
  {
    title: "Mop and Bucket",
    price: 34.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/mop-and-bucket-r3lHrcEWpIqfm75eFYqseLdbJdLZRE.jpg",
    description: "Keep your floors sparkling clean with our convenient and effective Mop and Bucket set. Designed to make mopping easier and more efficient, it features a high-quality mop with a super-absorbent, machine-washable microfiber head that effectively cleans up dirt, dust, and spills. The specially designed bucket has a built-in wringer to easily control the amount of water, ensuring your floors dry quickly and without streaks. This set is a practical and affordable solution for maintaining a clean and healthy home, perfect for hardwood, tile, or laminate floors.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-08-25"),
  },
  {
    title: "Lamp",
    price: 44.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/mop-and-bucket-r3lHrcEWpIqfm75eFYqseLdbJdLZRE.jpg",
    description: "Illuminate your space with our stylish and versatile Lamp. Designed to provide both functional and ambient lighting, it's a perfect addition to any room. The classic design and neutral color complement a variety of decor styles. It features a sturdy base and a fabric shade that diffuses the light to create a warm, inviting glow. The convenient on/off switch is located on the cord. This lamp is the perfect choice for a living room, bedroom, or office, adding a touch of style and warmth to any space. It's a practical and stylish investment in your home's comfort.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-24"),
  },
  {
    title: "Wall Clock",
    price: 24.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/modern-wall-clock-CFKjjDwR11Q6QfpkP8yegZatLDQyuo.png",
    description: "Keep track of time in style with our modern and minimalist Wall Clock. It's designed to be a functional and stylish addition to any room. The simple, clean design features a large, easy-to-read face with bold numbers and hands. The silent, non-ticking movement ensures a quiet and peaceful environment. Crafted from high-quality materials, its sleek, modern design complements a variety of decor styles. This wall clock is the perfect choice for a kitchen, living room, or office, adding a touch of style and functionality to any space.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-08-23"),
  },
  {
    title: "Throw Pillow",
    price: 29.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/throw-pillow-qinXsUenOpylnYsRgT14LgLLvNXt18.jpg",
    description: "Add a touch of comfort and style to your living space with our cozy and decorative Throw Pillow. It's the perfect accent for your sofa, bed, or armchair. Crafted from a soft, durable fabric and filled with a plush polyester fill, it features a stylish, modern design with a variety of colors and patterns to choose from. The removable cover with a hidden zipper makes it easy to clean. This throw pillow is a simple and affordable way to add a pop of color, texture, and personality to any room, creating a more inviting space.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-22"),
  },
  {
    title: "Curtains",
    price: 59.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/curtains-2rb3BtpxXKy65nSmBQkjXwX8d2lyNC.jpg",
    description: "Enhance your privacy and control the light in your room with our stylish and functional Curtains. They are a beautiful and practical addition to any room. Crafted from high-quality, light-filtering or blackout fabric, they can either gently diffuse light or completely block it out. The curtains feature a classic rod-pocket or grommet top design for easy hanging. The set includes two panels for full coverage. Available in a variety of colors and patterns, these machine-washable curtains are a simple and affordable way to add style and privacy to your home.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-21"),
  },
  {
    title: "Rug",
    price: 79.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/rug-5QZK6fVN4tD3y6qiqRqs0jBfZXSXry.jpg",
    description: "Add warmth, comfort, and style to your living space with our beautiful and durable Rug. It's the perfect centerpiece for any room. Crafted from a high-quality, soft, and durable material, it's both comfortable underfoot and easy to clean. The rug features a stylish, modern design with a variety of colors and patterns to choose from. A non-slip backing keeps it in place, reducing the risk of slips. Available in various sizes, this rug is a simple and affordable way to update your decor and create a more inviting and comfortable space.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-20"),
  },
  {
    title: "Bookshelf",
    price: 99.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/bookshelf-4ztlDPHY4CHCdHqtMLfCzXRRaWLnEk.jpg",
    description: "Organize your books and display your favorite decor with our stylish and functional Bookshelf. It's a beautiful and practical addition to any room. Crafted from a high-quality, durable material, it provides a sturdy, long-lasting design. The bookshelf features multiple shelves of varying heights, offering ample space for books, photos, and other items. The open design creates a light, airy feel, perfect for smaller spaces. With its sleek, modern design, this bookshelf is a simple and affordable way to add style and organization to any room, creating a more personalized and inviting space.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-19"),
  },
  {
    title: "Coffee Table",
    price: 129.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/modern-coffee-table-tut4uunLJgGXj1ksl1I5pRWOf2J5jT.png",
    description: "Complete your living room with our modern and stylish Coffee Table. It's designed to be a functional and beautiful centerpiece. Crafted from a high-quality, durable material, it provides a sturdy, long-lasting design. The spacious tabletop offers ample space for drinks, snacks, and decor, while the lower shelf provides additional storage for books and magazines. The sleek, modern design complements a variety of decor styles. This coffee table is the perfect way to add a touch of style and functionality to your living room, creating a more inviting and comfortable space.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-18"),
  },
  {
    title: "Dining Chair",
    price: 89.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/dining-chair-HoibG8V8xSAP4uQRXZWQWEvO4PHzbF.jpg",
    description: "Dine in comfort and style with our elegant and comfortable Dining Chair. It's a beautiful and practical addition to your dining room. Crafted from a high-quality, durable material, it features a comfortable, upholstered seat. The classic design and neutral color complement a variety of decor styles. Sturdy construction ensures this chair will be a long-lasting, reliable part of your dining room. It's the perfect choice for creating a beautiful and inviting dining experience, a simple and affordable way to update your decor and create a more comfortable, stylish dining space.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-17"),
  },
  {
    title: "Moisturizer",
    price: 34.99,
    category: "Beauty & Personal Care",
    image: "https://dr.rashel.in/cdn/shop/files/Hyaluronicacidmoisturizercream_1024x1024.jpg?v=1712218398",
    description: "Hydrate and nourish your skin with our luxurious and effective Moisturizer. Formulated with high-quality, natural ingredients, it provides long-lasting hydration and improves your skin's overall health. The lightweight, non-greasy formula absorbs quickly, leaving your skin soft and supple. Enriched with hyaluronic acid and antioxidants like vitamin E, it helps to plump skin, reduce fine lines, and protect against environmental damage. Suitable for all skin types, this gentle, daily-use formula is the perfect final step in your skincare routine, locking in moisture and creating a smooth canvas for makeup.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-16"),
  },
  {
    title: "Sunscreen SPF 50",
    price: 24.99,
    category: "Beauty & Personal Care",
    image: "https://www.newu.in/cdn/shop/files/1_e220deed-7886-4b7f-ad8f-2fb41a469824_1024x1024.jpg?v=1737721311",
    description: "Protect your skin from the sun's harmful rays with our high-performance Sunscreen SPF 50. This broad-spectrum sunscreen provides superior protection against both UVA and UVB rays, preventing sunburn and premature aging. The lightweight, non-greasy formula absorbs quickly and leaves no white cast, making it perfect for everyday use. It's water-resistant for up to 80 minutes and enriched with antioxidants to protect your skin from environmental damage. This reef-safe, hypoallergenic formula is suitable for all skin types. Enjoy the sun with confidence, knowing your skin is protected with this essential daily skincare product.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-08-15"),
  },
  {
    title: "Shampoo",
    price: 14.99,
    category: "Beauty & Personal Care",
    image: "https://www.thedravyastore.com/cdn/shop/files/8K2A8864-1-1-scaled_1024x1024.jpg?v=1719758325",
    description: "Cleanse and nourish your hair with our gentle and effective Shampoo. Formulated with natural ingredients, it removes dirt, oil, and buildup without stripping your hair of its natural oils. The gentle, sulfate-free formula is suitable for all hair types, including color-treated hair. Enriched with botanical extracts and essential oils, it strengthens, hydrates, and protects your hair. With regular use, your hair will be softer, shinier, and more manageable. The refreshing scent leaves your hair smelling clean and fresh. It's the perfect first step in your hair care routine for clean, healthy, and beautiful hair.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-14"),
  },
  {
    title: "Conditioner",
    price: 14.99,
    category: "Beauty & Personal Care",
    image: "https://heyumanos.com/cdn/shop/files/umanosConditionerBottleBox_1024x1024.jpg?v=1719353171",
    description: "Hydrate and detangle your hair with our rich and nourishing Conditioner. Formulated with natural ingredients, it moisturizes, strengthens, and protects your hair. The creamy formula smooths the hair cuticle, reducing frizz and leaving your hair soft, silky, and manageable. Enriched with botanical extracts and essential oils, it helps repair damage and prevent breakage. Suitable for all hair types, including color-treated hair, this sulfate-free conditioner will leave your hair with a beautiful, healthy shine. It's the perfect second step in your hair care routine for hydrated, healthy, and beautiful hair.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-13"),
  },
  {
    title: "Face Mask",
    price: 19.99,
    category: "Beauty & Personal Care",
    image: "https://nirvanabeing.com/cdn/shop/products/blueleft_1024x1024.png?v=1699527428",
    description: "Treat your skin to a spa-like experience with our luxurious and effective Face Mask. Formulated with natural ingredients, it detoxifies, hydrates, and rejuvenates your skin. The creamy formula is easy to apply and feels cool and refreshing. Enriched with clay to draw out impurities and botanical extracts to soothe and nourish, this mask is suitable for all skin types. With regular use, your skin will be softer, smoother, and more radiant. It's the perfect way to pamper yourself and achieve a healthy, glowing complexion. Give your skin the extra love it deserves.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-12"),
  },
  {
    title: "Lipstick",
    price: 16.99,
    category: "Beauty & Personal Care",
    image: "https://www.lagirlusa.com/cdn/shop/products/GLC581_prod_img_1024x1024.jpg?v=1699773955",
    description: "Add a pop of color to your look with our vibrant and long-lasting Lipstick. Formulated with high-quality pigments and moisturizing ingredients, it provides rich, beautiful color and a comfortable, hydrating feel. The creamy formula glides on smoothly, offering full coverage in a single swipe. Available in a wide range of shades, from classic nudes to bold reds, you can find the perfect one to match your mood. The long-lasting formula stays put for hours without feathering or fading. It's the perfect way to complete your makeup look and express your personal style.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-11"),
  },
  {
    title: "Foundation",
    price: 29.99,
    category: "Beauty & Personal Care",
    image: "https://www.facescanada.com/cdn/shop/products/UltimeProHDRunwayReadyFoundation_PDP_Ivory_1024x1024.jpg?v=1646397623",
    description: "Create a flawless canvas for your makeup with our lightweight and buildable Foundation. It provides natural-looking, medium-to-full coverage that evens out your skin tone and conceals imperfections. The lightweight, oil-free formula blends seamlessly into your skin for a smooth, natural finish. Available in a wide range of shades, its long-lasting formula stays put all day without caking or creasing. Enriched with skin-loving ingredients, it's suitable for all skin types, including sensitive skin. This foundation is the perfect base for any makeup look, helping you achieve a flawless, radiant complexion.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-10"),
  },
  {
    title: "Eye Shadow Palette",
    price: 24.99,
    category: "Beauty & Personal Care",
    image: "https://hokmakeup.com/cdn/shop/files/G43312_prod_img_1024x1024_ab08b91c-7fd8-4b4b-9271-5253ce8d112e.jpg?v=1757405008",
    description: "Create stunning eye looks with our versatile and highly-pigmented Eye Shadow Palette. It features a curated collection of shades in a range of finishes, from matte and satin to shimmer and metallic. The smooth, blendable formula is easy to apply and provides rich, long-lasting color. Available in a variety of color stories, you can find the perfect one to match your style and create looks from natural to dramatic. The compact, travel-friendly packaging makes it easy to take on the go. This palette is the perfect tool for any makeup lover.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-09"),
  },
  {
    title: "Mascara",
    price: 12.99,
    category: "Beauty & Personal Care",
    image: "https://swissbeauty.in/cdn/shop/files/Select_Game_Changer_Tubing_Mascara_1024x.jpg?v=1759300833",
    description: "Define and lengthen your lashes with our volumizing and lengthening Mascara. It's formulated to provide dramatic volume and length without clumping or flaking. The specially designed brush coats each lash from root to tip, creating a full, fluttery look. The long-lasting, water-resistant formula stays put all day without smudging or smearing. Available in a classic black shade, this mascara is the perfect finishing touch to any eye makeup look. It's a simple and effective way to make your eyes look bigger, brighter, and more awake, whether you're going for a natural or dramatic look.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-08"),
  },
  {
    title: "Perfume",
    price: 49.99,
    category: "Beauty & Personal Care",
    image: "https://www.lylablanc.in/cdn/shop/files/WhatsAppImage2025-06-26at3.45.22PM.jpg?v=1750932942",
    description: "Leave a lasting impression with our captivating and long-lasting Perfume. This fragrance is a beautiful blend of floral, fruity, and woody notes, creating a unique and unforgettable scent. The top notes are bright and fresh, the middle notes are soft and feminine, and the base notes are warm and sensual. The long-lasting formula stays with you all day, leaving a beautiful, lingering trail. The elegant bottle is a beautiful addition to any vanity. This perfume is the perfect way to express your personal style and feel confident and beautiful.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-08-07"),
  },
  {
    title: "Body Lotion",
    price: 19.99,
    category: "Beauty & Personal Care",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMIvH9WskCdy_Ya96TJnv-SkhpCefGiYjzKA&s",
    description: "Hydrate and nourish your skin with our rich and creamy Body Lotion. Formulated with natural ingredients, it provides long-lasting hydration and improves your skin's overall health. The non-greasy formula absorbs quickly, leaving your skin soft, smooth, and supple. Enriched with shea butter and vitamin E, it moisturizes and protects. Suitable for all skin types, this gentle, daily-use lotion will significantly improve your skin's texture and tone. The light, refreshing scent leaves your skin smelling clean and fresh. It's the perfect way to pamper your skin and keep it looking and feeling its best.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-06"),
  },
  {
    title: "Toothbrush",
    price: 9.99,
    category: "Beauty & Personal Care",
    image: "https://cdn-ilbepif.nitrocdn.com/pZrBMYQGrUZaHsbVKBUlrVMHXHFmMxDe/assets/images/optimized/rev-5919f9c/organicb.in/wp-content/uploads/2024/07/BrushYourWaytoaBrighterSmileandaGreenerPlanetYourGuidetoEco-FriendlyToothbrushes-1024x1024.jpg",
    description: "Keep your teeth and gums healthy with our effective and gentle Toothbrush. It's designed to provide a thorough, comfortable clean. The soft, rounded bristles are gentle on your gums and effective at removing plaque and food particles. The ergonomic handle provides a comfortable, secure grip. Available in a variety of colors, this toothbrush is the perfect choice for anyone who wants to maintain good oral hygiene. It's a simple and affordable way to keep your teeth and gums healthy. For best results, use with our matching toothpaste and replace your toothbrush every three months.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-08-05"),
  },
  {
    title: "Toothpaste",
    price: 7.99,
    category: "Beauty & Personal Care",
    image: "https://himalayawellness.in/cdn/shop/products/sparkling-white-toothpaste_1024x1024.jpg?v=1622095538",
    description: "Achieve a brighter, healthier smile with our whitening and strengthening Toothpaste. Formulated with natural ingredients, it gently whitens your teeth, removes stains, and strengthens your enamel. The fluoride formula helps prevent cavities and protect your teeth from decay. A refreshing mint flavor leaves your mouth feeling clean and fresh. This toothpaste is the perfect choice for anyone who wants to achieve a brighter, healthier smile. It's a simple and effective way to improve your oral hygiene and boost your confidence. For best results, use with our matching toothbrush and visit your dentist regularly.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-08-04"),
  },
  {
    title: "Deodorant",
    price: 8.99,
    category: "Beauty & Personal Care",
    image: "https://www.wildstone.in/cdn/shop/files/Edge150mlnew-Copy_1_1024x1024.jpg?v=1688560465",
    description: "Stay fresh and confident all day long with our effective and long-lasting Deodorant. It's formulated to provide 24-hour protection against odor and wetness. The gentle, non-irritating formula is suitable for all skin types, including sensitive skin, and is free of aluminum and parabens. It glides on smoothly and dries quickly, leaving no white marks on your clothes. The light, refreshing scent will leave you feeling clean and confident. This deodorant is the perfect choice for anyone who wants to stay fresh and dry all day long. Stay confident and comfortable.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-03"),
  },
  {
    title: "Hair Serum",
    price: 22.99,
    category: "Beauty & Personal Care",
    image: "https://trichocarepharma.com/wp-content/uploads/2024/07/Artboard-1-copy-6-1024x1024.webp",
    description: "Tame frizz, add shine, and protect your hair with our lightweight and nourishing Hair Serum. Formulated with natural oils and silicones, it smooths the hair cuticle, reduces frizz, and adds a beautiful, healthy shine. The non-greasy formula won't weigh your hair down and is suitable for all hair types. Use on damp or dry hair to tame flyaways, add shine, and protect from heat damage. This hair serum is the perfect finishing touch for any hairstyle, a simple and effective way to achieve smooth, shiny, and healthy-looking hair.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-02"),
  },
  {
    title: "Face Cleanser",
    price: 16.99,
    category: "Beauty & Personal Care",
    image: "https://www.fixderma.com/cdn/shop/files/mandefix_foaming_face_wash_50ml.webp?v=1756383750",
    description: "Cleanse and refresh your skin with our gentle and effective Face Cleanser. Formulated with natural ingredients, it removes dirt, oil, and makeup without stripping your skin of its natural moisture. The gentle, non-foaming formula is suitable for all skin types, including sensitive skin, and is free of sulfates and parabens. Enriched with botanical extracts, it soothes and nourishes your skin. With regular use, you'll notice a significant improvement in your skin's clarity and texture. It's the perfect first step in your skincare routine for clean, healthy, and beautiful skin.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-01"),
  },
  {
    title: "Exfoliator",
    price: 18.99,
    category: "Beauty & Personal Care",
    image: "https://mantleskin.com/cdn/shop/files/Mantle_TheEx_1024x1024.jpg?v=1754895116",
    description: "Reveal a brighter, smoother complexion with our gentle and effective Exfoliator. Formulated with natural ingredients, it gently removes dead skin cells and unclogs pores. The fine, gentle exfoliating particles are suitable for all skin types, including sensitive skin. Enriched with botanical extracts, it soothes and nourishes your skin. With regular use, you'll notice a significant improvement in your skin's clarity, texture, and overall health. It will be softer, smoother, and more radiant. This exfoliator is the perfect way to achieve a healthy, glowing complexion and reveal your skin's natural radiance.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-31"),
  },
  {
    title: "Nail Polish",
    price: 9.99,
    category: "Beauty & Personal Care",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/c_crop,w_1024,h_1024/v1761152704/ed6a3eb3-94d0-4b58-bafa-44a422eb346e1718365080024ModelonesColoringLifeSoak-OffUVLEDCuredGelNailPolish7ml-MD-11_p0bsti.webp",
    description: "Add a pop of color to your nails with our vibrant and long-lasting Nail Polish. Formulated with high-quality pigments, it provides rich, beautiful color in a single coat. The chip-resistant formula is designed to last for days without chipping or fading. Available in a wide range of shades, from classic nudes to bold reds and blues, you can find the perfect one to match your mood. The easy-to-use brush provides a smooth, even application. This nail polish is the perfect way to complete your look and express your personal style.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-30"),
  },
  {
    title: "Nail File Set",
    price: 12.99,
    category: "Beauty & Personal Care",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_n7dusMz72u1kF2exXNYWu2upchLKgPsKsg&s",
    description: "Keep your nails looking their best with our comprehensive Nail File Set. It includes a variety of files and buffers for all your nail care needs. The files are designed to shape and smooth your nails, while the buffers create a high-shine finish. Housed in a convenient, travel-friendly case, this set is the perfect tool for any at-home manicure. It's a simple and affordable way to keep your nails looking healthy and beautiful. Whether you're a nail care enthusiast or just want to maintain neat and tidy nails, this set is the perfect choice.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-07-29"),
  },
  {
    title: "Hair Brush",
    price: 14.99,
    category: "Beauty & Personal Care",
    image: "https://www.kareco.com/cdn/shop/products/BigHairBrushCollection_1024x1024.png?v=1659635651",
    description: "Detangle and style your hair with our gentle and effective Hair Brush. It's designed for all hair types, from fine and straight to thick and curly. The flexible bristles are gentle on your hair and scalp, working to detangle knots and smooth frizz. The ergonomic handle provides a comfortable, secure grip. This hair brush is the perfect tool for everyday styling, a simple and affordable way to keep your hair looking its best. Whether you're brushing your hair in the morning, after a shower, or before bed, this hair brush is the perfect choice.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-28"),
  },
  {
    title: "Yoga Mat",
    price: 29.99,
    category: "Sports & Fitness",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhA60xCxttg3dtVwiuRJxk1psNe_p8QjZO4w&s",
    description: "Enhance your yoga practice with our premium Yoga Mat. It provides the perfect balance of comfort, stability, and grip, making it essential for yogis of all levels. Crafted from a high-quality, eco-friendly material, it's both durable and lightweight. The non-slip surface ensures you stay stable in every pose, while the thick, cushioned design provides comfort for your joints. Easy to clean and maintain, it includes a carrying strap for easy transport. This yoga mat is a simple and affordable way to invest in your health and well-being, perfect for any yogi.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-27"),
  },
  {
    title: "Dumbbells Set",
    price: 79.99,
    category: "Sports & Fitness",
    image: "https://samsfitness.com.au/wp-content/smush-webp/2020/09/CGHEXDB30KG-rubber-hex-dumbbell-pair-1024x1024.jpg.webp",
    description: "Build strength and tone your muscles with our versatile Dumbbells Set. This set includes a pair of dumbbells in a variety of weights, perfect for a wide range of exercises and fitness levels. Crafted from a high-quality, durable material, their hexagonal shape prevents rolling, making them a safe choice for your home gym. The ergonomic, textured handles provide a comfortable, secure grip. This dumbbells set is the perfect choice for anyone who wants to build strength, tone muscles, and improve their overall fitness. It's a simple and effective way to get a full-body workout at home.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-07-26"),
  },
  {
    title: "Resistance Bands",
    price: 19.99,
    category: "Sports & Fitness",
    image: "https://slovicfitness.com/cdn/shop/files/Blue_1024x1024.jpg?v=1703061610",
    description: "Add variety and intensity to your workouts with our versatile Resistance Bands. This set includes bands with different resistance levels, perfect for a wide range of exercises and fitness levels. Crafted from a high-quality, durable latex material, they are strong and flexible. Perfect for strength training, physical therapy, and stretching. The compact, lightweight design makes them easy to take on the go. This set is a simple and affordable way to build strength, improve flexibility, and achieve your fitness goals. These bands are sure to become an essential part of your fitness routine.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-25"),
  },
  {
    title: "Jump Rope",
    price: 14.99,
    category: "Sports & Fitness",
    image: "https://www.bullrockfitness.com/wp-content/uploads/2024/12/1_Aluminium_Jump_Rope_self_Lock-1024x1024.jpg",
    description: "Get your heart pumping and improve your coordination with our high-quality Jump Rope. Designed for speed and durability, it features a lightweight, adjustable cable and smooth-spinning ball bearings. The comfortable, ergonomic handles provide a secure grip. Its adjustable length makes it suitable for people of all heights. This jump rope is the perfect choice for anyone who wants a great cardio workout. It's a simple and affordable way to improve your fitness and burn calories. Whether you're a beginner or an experienced jumper, this jump rope is an essential part of any fitness routine.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-24"),
  },
  {
    title: "Kettlebell",
    price: 34.99,
    category: "Sports & Fitness",
    image: "https://commercial.torquefitness.com/cdn/shop/files/2024_06_06-35LBRubberCoatedKettlebell-5832_1024x1024.jpg?v=1745251179",
    description: "Build strength, power, and endurance with our versatile Kettlebell. It's designed for a wide range of exercises, from swings and squats to presses and rows. Crafted from a high-quality, durable material, it provides a long-lasting, reliable design. The wide, flat base offers a stable platform for various exercises, and the comfortable, ergonomic handle ensures a secure grip. This kettlebell is the perfect choice for building functional strength and improving your overall fitness. It's a simple and effective way to get a full-body workout at home, essential for any fitness routine.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-23"),
  },
  {
    title: "Pull-up Bar",
    price: 44.99,
    category: "Sports & Fitness",
    image: "https://www.bullrockfitness.com/wp-content/uploads/2023/04/rig_flying_pull_up_bar-1024x1024.jpg",
    description: "Build upper body strength with our sturdy and easy-to-install Pull-up Bar. It's designed to fit most standard doorways, making it a convenient, space-saving choice for your home gym. Crafted from high-quality, durable steel, it can support up to 300 pounds. The comfortable, non-slip foam grips provide a secure grip. Use it for a variety of exercises, including pull-ups, chin-ups, and hanging leg raises. This pull-up bar is the perfect choice for anyone who wants to build upper body strength and improve their overall fitness. It's a simple and effective way to get a great workout at home.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-22"),
  },
  {
    title: "Ab Roller",
    price: 24.99,
    category: "Sports & Fitness",
    image: "https://www.strengthshop.co.uk/cdn/shop/products/new-ab-wheel_1024x1024.jpg?v=1641970945",
    description: "Strengthen your core and tone your abs with our effective and easy-to-use Ab Roller. It's designed to provide a challenging and effective core workout. Featuring a durable, non-slip wheel and comfortable, ergonomic handles, this ab roller is a simple and effective way to target your abs, obliques, and lower back. It's the perfect choice for anyone who wants to build a strong core and achieve a toned stomach. A simple and affordable way to get a great core workout at home, this ab roller is an essential part of any fitness routine.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-21"),
  },
  {
    title: "Foam Roller",
    price: 29.99,
    category: "Sports & Fitness",
    image: "https://worldfitness.com.au/cdn/shop/products/TriggerPointGRID2.0FoamRoller_1024x1024.png?v=1662693538",
    description: "Relieve muscle soreness and improve your flexibility with our versatile Foam Roller. It's designed for self-myofascial release, a form of massage that helps reduce muscle tension and improve range of motion. Crafted from a high-density foam material, it's both durable and comfortable. Use it on a variety of muscle groups, including the back, legs, and arms. This foam roller is the perfect choice for improving recovery and reducing muscle soreness. It's a simple and effective way to take care of your body and improve your overall well-being, essential for any recovery routine.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-20"),
  },
  {
    title: "Gym Bag",
    price: 39.99,
    category: "Sports & Fitness",
    image: "https://fabrella.in/cdn/shop/files/m-iron-man-2020-monvelli-25-original-imag5dzanbyes3cw_1024x1024.jpg?v=1738867588",
    description: "Carry your gym essentials in style with our spacious and durable Gym Bag. It's both functional and fashionable, with a variety of compartments and pockets to keep your gear organized. The spacious main compartment is perfect for your clothes, shoes, and towel, while smaller pockets hold your phone, wallet, and keys. It also features a separate, ventilated compartment for wet clothes or shoes. The adjustable shoulder strap and comfortable handles make it easy to carry. This gym bag is a stylish and practical way to stay organized and look good at the gym.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-19"),
  },
  {
    title: "Water Bottle",
    price: 19.99,
    category: "Sports & Fitness",
    image: "https://www.milton.in/cdn/shop/files/Texture1024x1024.png?v=1735194226",
    description: "Stay hydrated during your workouts with our durable and convenient Water Bottle. It's designed to be both leak-proof and easy to drink from. Crafted from high-quality, BPA-free plastic, it's lightweight and long-lasting. The flip-top lid with a secure lock makes it easy to open and close with one hand. A wide mouth makes it easy to add ice and clean, and it features a convenient carrying loop. This water bottle is the perfect choice for staying hydrated during workouts, a simple and affordable way to ensure you're getting enough water throughout the day.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-18"),
  },
  {
    title: "Protein Shaker",
    price: 12.99,
    category: "Sports & Fitness",
    image: "https://zenithsports.in/cdn/shop/products/MainBanner.jpg?v=1632117877",
    description: "Mix your protein shakes and supplements with ease using our convenient and leak-proof Protein Shaker. It's designed to be both easy to use and easy to clean. Featuring a secure, screw-on lid and a snap-on cap to prevent leaks, it also includes a mixing ball to break up clumps and create a smooth shake. Crafted from high-quality, BPA-free plastic, it's durable and dishwasher-safe. This protein shaker is the perfect choice for a simple and effective way to mix your supplements, an essential part of any fitness routine.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-17"),
  },
  {
    title: "Yoga Blocks",
    price: 16.99,
    category: "Sports & Fitness",
    image: "https://cdn.yanrefitness.com/cdn-cgi/imagedelivery/m94-xP3Y6Xwv_FOE9Rj47w/www.yanrefitness.com/2021/07/Figure-1-Cork-yoga-Blocks.jpg/w=1024",
    description: "Deepen your stretches and improve your alignment with our supportive and durable Yoga Blocks. This set of two blocks is designed to provide stability and support in a variety of yoga poses. Crafted from a high-density foam material, they are both lightweight and sturdy. Use them to support your hands, feet, or hips, helping you to achieve deeper stretches and better alignment. This yoga blocks set is the perfect choice for improving your yoga practice, a simple and affordable way to take your practice to the next level, essential for any yogi.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-16"),
  },
  {
    title: "Yoga Strap",
    price: 12.99,
    category: "Sports & Fitness",
    image: "https://msfstore.fit/cdn/shop/files/Yoga_Strap_With_SS_Hook_A1_1_1024x1024.jpg?v=1740553059",
    description: "Improve your flexibility and deepen your stretches with our durable and adjustable Yoga Strap. It's designed to help you reach further and hold poses for longer. Crafted from a high-quality, non-stretch cotton material, it's both strong and comfortable. The adjustable D-ring buckle allows you to easily adjust the length to suit your needs. This yoga strap is the perfect choice for anyone who wants to improve their flexibility and deepen their yoga practice. It's a simple and affordable way to take your practice to the next level, essential for any yogi.",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-07-15"),
  },
  {
    title: "Fitness Tracker",
    price: 99.99,
    category: "Sports & Fitness",
    image: "https://www.fabmart.com/cdn/shop/products/fitness-trackers-getactive-fitness-tracker-3_1024x1024.jpeg?v=1476774294",
    description: "Track your activity and monitor your health with our advanced Fitness Tracker. It's designed to help you achieve your fitness goals and live a healthier lifestyle. It tracks your steps, distance, calories burned, and active minutes, and also monitors your heart rate and sleep patterns. The tracker syncs with your smartphone to provide detailed data and insights. Its sleek, lightweight design is comfortable to wear all day and night, and the long-lasting battery provides up to 7 days of use. This fitness tracker is a simple and effective way to stay motivated and achieve your goals.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-14"),
  },
  {
    title: "Skipping Rope",
    price: 16.99,
    category: "Sports & Fitness",
    image: "https://www.bullrockfitness.com/wp-content/uploads/2024/12/1_Aluminium_Jump_Rope_self_Lock-1024x1024.jpg",
    description: "Get a great cardio workout with our durable and adjustable Skipping Rope. Designed for speed and performance, it features a lightweight, tangle-free cable and smooth-spinning ball bearings. The comfortable, ergonomic handles provide a secure grip. Its adjustable length makes it suitable for people of all heights. This skipping rope is the perfect choice for a great cardio workout, a simple and affordable way to improve your fitness and burn calories. Whether you're a beginner or an experienced jumper, this skipping rope is an essential part of any fitness routine.",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-13"),
  },
  {
    title: "Punching Bag",
    price: 59.99,
    category: "Sports & Fitness",
    image: "https://m.media-amazon.com/images/I/81yKBX5LLZL._UF1000,1000_QL80_.jpg",
    description: "Get a great workout and relieve stress with our durable and high-quality Punching Bag. Designed for both beginners and experienced boxers, it's crafted from a durable, synthetic leather material that can withstand the toughest punches and kicks. The bag is filled with high-density foam for excellent shock absorption. Heavy-duty straps and D-rings ensure it's securely hung. This punching bag is the perfect choice for improving your boxing skills and getting a full-body workout at home. It's an essential part of any fitness routine, whether you're a seasoned boxer or just starting out.",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-12"),
  },
  {
    title: "Boxing Gloves",
    price: 44.99,
    category: "Sports & Fitness",
    image: "https://www.fightequipmentuk.com/cdn/shop/files/playerz-spartech-boxing-gloves-whiteblack-playerz-boxing.jpg?v=1743656385",
    description: "Protect your hands and improve your performance with our high-quality Boxing Gloves. Designed for both training and sparring, they are crafted from a durable, synthetic leather material and feature multi-layer foam padding for excellent shock absorption. The secure, hook-and-loop closure provides a snug, comfortable fit. Available in a variety of sizes and weights, you can find the perfect pair for your needs. These boxing gloves are the perfect choice for taking your training to the next level, a simple and effective way to protect your hands and improve your performance.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-11"),
  },
  {
    title: "Resistance Loop Bands",
    price: 14.99,
    category: "Sports & Fitness",
    image: "https://commercial.torquefitness.com/cdn/shop/products/LBT9_main_1024x1024.jpg?v=1670362452",
    description: "Add resistance to your workouts with our versatile Resistance Loop Bands. This set includes bands with different resistance levels, perfect for a wide range of exercises and fitness levels. Crafted from a high-quality, durable latex material, they are strong and flexible. Perfect for strength training, physical therapy, and stretching. The compact, lightweight design makes them easy to take on the go. This set is a simple and affordable way to build strength, improve flexibility, and achieve your fitness goals. These resistance loop bands are an essential part of any fitness routine.",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-10"),
  },
  {
    title: "Exercise Ball",
    price: 24.99,
    category: "Sports & Fitness",
    image: "https://www.msffit.com/cdn/shop/files/Anti-Burst_Exercise_Balls_1_1024x1024.jpg?v=1740565246",
    description: "Improve your balance, stability, and core strength with our durable and versatile Exercise Ball. It's designed for a wide range of exercises, from core work and stretching to yoga and Pilates. Crafted from a high-quality, anti-burst material, it can support up to 600 pounds. The non-slip surface provides a secure grip. Available in a variety of sizes, you can find the perfect one for your height. This exercise ball is the perfect choice for improving your fitness and overall well-being, a simple and effective way to get a full-body workout at home.",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-09"),
  },
  {
    title: "Massage Gun",
    price: 89.99,
    category: "Sports & Fitness",
    image: "https://healthsense.in/cdn/shop/files/Main_image_1024x1024.jpg?v=1719389910",
    description: "Relieve muscle soreness and improve your recovery with our powerful and portable Massage Gun. It provides deep tissue massage, helping to reduce muscle tension and improve circulation. Featuring a powerful, high-torque motor and multiple speed settings, you can customize the intensity of your massage. It includes a variety of interchangeable heads to target different muscle groups. The lightweight, ergonomic design makes it easy to use. The long-lasting battery provides up to 3 hours of use on a single charge. This massage gun is the perfect choice for improving recovery and reducing muscle soreness.",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-07-08"),
  }]
const productsJSON = JSON.stringify(products);
console.log(productsJSON);
export default productsJSON