const products = [{
    title: "Smart Fitness Watch",
    price: 249.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143299/smart-fitness-watch-jfrqIkFjNxfMz2FpRB5htLYKHhw8kY_jggtue.jpg",
    rating: 5.0,
    reviews: [],
    createdAt: new Date("2025-10-15"),
  },
  {
    title: "Wireless Earbuds Pro",
    price: 179.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143517/wireless-earbuds-pro-oKPqM9oN60Lib7jpOe92GqxI5egWdH_bv9q4z.jpg",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-10-14"),
  },
  {
    title: "4K Webcam",
    price: 129.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143706/4k-webcam-E8uStGVcj7MGvaxdhxiLyFdYaPgIwh_hexgty.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-10-13"),
  },
  {
    title: "USB-C Hub",
    price: 49.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143863/usb-c-hub-kIWXrZ0JSjlIIic9AaQqPXB3pFFAzb_kwvaqu.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-10-12"),
  },
  {
    title: "Mechanical Keyboard",
    price: 159.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143906/mechanical-keyboard-IXU7mTfsOdw9FvR7Fh3qpQULw0AP7R_adzvns.jpg",
    rating: 4.9,
    reviews: [],
    createdAt: new Date("2025-10-11"),
  },
  {
    title: "Wireless Mouse",
    price: 39.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761143952/wireless-mouse-gaYSdYszQdxE3riM1dHTIR8Wg8mVLS_hdbdbk.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-10-10"),
  },
  {
    title: "Portable SSD 1TB",
    price: 99.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144000/portable-ssd-1tb-0d5ECzoXdqA5M7WZkDeBTCVOLopEKQ_iix9fx.jpg",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-10-09"),
  },
  {
    title: "Laptop Stand",
    price: 29.99,
    category: "Electronics",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/laptop-stand-UZwVML7JKLStw6NPbvydtfVzegEagp.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-10-08"),
  },
  {
    title: "Portable Charger 20000mAh",
    price: 34.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144093/portable-charger-20000mah-YNA4lKuklHzgOUpMny2vsky8HiA8cK_vtivcu.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-10-07"),
  },
  {
    title: "Bluetooth Speaker",
    price: 79.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144146/bluetooth-speaker-fkonqloSW5rgNnI42W53u864qTmlZO_hmlpet.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-10-06"),
  },
  {
    title: "Wireless Charger",
    price: 24.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144180/wireless-charger-cAhfJTX7WE8xIXDsj05hvZ2eOgrLG9_dtcqbm.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-10-05"),
  },
  {
    title: "USB-C Cable 3-Pack",
    price: 19.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144217/usb-c-cable-3pack-sqWWYTQFRGFhRSCISUWoveSGBfBbXc_vxkuxd.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-10-04"),
  },
  {
    title: "Screen Protector Pack",
    price: 14.99,
    category: "Electronics",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/screen-protector-pack-TkpNIqaZCLk7FtwlcwAqXbfDmwsvzY.jpg",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-10-03"),
  },
  {
    title: "Phone Case",
    price: 19.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144286/phone-case-NvZDfGEWqmXg8F1RNsk29yCd0Qcrkd_qn5jvs.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-10-02"),
  },
  {
    title: "Tablet Stand",
    price: 22.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144330/tablet-stand-kO5tR2A8FeKj2pxRhaoa5sliOPz5m6_z8yvlx.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-10-01"),
  },
  {
    title: "HDMI Cable 2-Pack",
    price: 16.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144513/61JL7RYC18L._UF1000_1000_QL80__bfczs6.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-09-30"),
  },
  {
    title: "Monitor Light Bar",
    price: 89.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144732/Pura_Monitor_Light_Bar_7_1024x1024_jxsahq.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-29"),
  },
  {
    title: "Webcam Ring Light",
    price: 34.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/c_crop,w_1024,h_1024/v1761144801/RingLight18_01_gzj9zb.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-28"),
  },
  {
    title: "Desk Lamp",
    price: 44.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144903/executivetablelamp_b1j31a.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-27"),
  },
  {
    title: "Cable Organizer",
    price: 12.99,
    category: "Electronics",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/v1761144970/realike-travel-cable-organizer-electronic-accessories-organizer-for-cord-hard-drive-earphone-power-bank-and-others-13469066461284_1024x1024_isxeox.jpg",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-09-26"),
  },

  // Fashion & Apparel - 20 products
  {
    title: "Classic White T-Shirt",
    price: 29.99,
    category: "Fashion & Apparel",
    image: "https://cdn.thewirecutter.com/wp-content/media/2025/09/BEST-MENS-WHITE-TEES-SUB-2048px-5935.jpg?auto=webp&quality=75&width=1024",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-25"),
  },
  {
    title: "Blue Denim Jeans",
    price: 79.99,
    category: "Fashion & Apparel",
    image: "https://www.mumkins.in/cdn/shop/products/denim-jeans-for-kids-bl0612345-darkblue-1_1024x1024.jpg?v=1757575343",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-24"),
  },
  {
    title: "Black Leather Jacket",
    price: 199.99,
    category: "Fashion & Apparel",
    image: "https://www.noorainternational.biz/cdn/shop/files/Myproject-1_5_1024x1024.jpg?v=1690871206",
    rating: 4.9,
    reviews: [],
    createdAt: new Date("2025-09-23"),
  },
  {
    title: "Summer Dress",
    price: 59.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/summer-dress-0VJHv3JqYlEwT6PXd7dRGTRSSwS76Q.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-22"),
  },
  {
    title: "Casual Hoodie",
    price: 49.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/casual-hoodie-fy6hMYb29TrBfW8JAQiJWo4Oqjkril.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-21"),
  },
  {
    title: "Running Shoes",
    price: 119.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/running-shoes-g0gyL1uiU320toVAxbwRNu5R8zkxF0.jpg",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-20"),
  },
  {
    title: "Formal Blazer",
    price: 149.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/formal-blazer-EPJ8kUYTNiuDFfq0ayYQdfutrVSjsE.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-19"),
  },
  {
    title: "Casual Sneakers",
    price: 89.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/casual-sneakers-qYGY9HdtSFR3cXHmOIIKx8PkChK2ER.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-18"),
  },
  {
    title: "Wool Sweater",
    price: 69.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/wool-sweater-k7dNfTXsCdEguuRASAJ6JyQw0M4gws.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-17"),
  },
  {
    title: "Cargo Pants",
    price: 74.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/cargo-pants-S5UmJ6tvjRjysdJZvXg54ZEQ4FZw1c.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-09-16"),
  },
  {
    title: "Polo Shirt",
    price: 44.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/polo-shirt-WChYflDB7ZTVwMa6FxOuKf8TZ4F00T.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-15"),
  },
  {
    title: "Leather Belt",
    price: 39.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/leather-belt-XqiNhkVB5r2LL29lGRnG14vWBu3lbd.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-14"),
  },
  {
    title: "Sunglasses",
    price: 99.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/sunglasses-V2Srj7WtRy7xjDv94mhk1wAQI47k6Q.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-13"),
  },
  {
    title: "Backpack",
    price: 79.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/backpack-T5L1l2mCl8tRSYRdojqa3JBdJZARZ5.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-12"),
  },
  {
    title: "Crossbody Bag",
    price: 59.99,
    category: "Fashion & Apparel",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/crossbody-bag-R3IGMGYCwMxA8VtoqS6imHdAr9aV8m.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-11"),
  },
  {
    title: "Winter Coat",
    price: 179.99,
    category: "Fashion & Apparel",
    image: "https://affairweatherkennel.com/wp-content/uploads/2024/06/Men_s-Hooded-Winter-Coat-Puffer-Jacket-Thicken-Warm-Fur-Down-Parka-Jacket-with-Removable-Hood_4-1024x1024.jpg",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-10"),
  },
  {
    title: "Shorts",
    price: 39.99,
    category: "Fashion & Apparel",
    image: "https://www.dukeindia.com/cdn/shop/files/5_03adfdfc-5669-41be-a4c5-e76024e3704d_1024x1024.jpg?v=1702463834",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-09-09"),
  },
  {
    title: "Scarf",
    price: 29.99,
    category: "Fashion & Apparel",
    image: "https://www.annabeltrends.com/cdn/shop/products/63SSB_Slip_through_Scarf_Black_2.jpg?v=1683872166",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-08"),
  },
  {
    title: "Watch",
    price: 149.99,
    category: "Fashion & Apparel",
    image: "https://m.media-amazon.com/images/I/61liwYpcANL._UY1000_.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-07"),
  },
  {
    title: "Gloves",
    price: 24.99,
    category: "Fashion & Apparel",
    image: "https://www.bestmarine.com/cdn/shop/files/PVCgloves_1024x1024.jpg?v=1744970541",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-09-06"),
  },

  // Home & Kitchen - 20 products
  {
    title: "Blender",
    price: 89.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/blender-epIlNICv0ESTjq0KtLAoPpYkOdYiu8.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-05"),
  },
  {
    title: "Coffee Maker",
    price: 79.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/coffee-maker-R1K2m4nrNJHrzXdgbqzbuBaE3cl8Nb.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-09-04"),
  },
  {
    title: "Cookware Set",
    price: 129.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/cookware-set-ugpyL0IK68PZTqjtE7hZvfBk12WMmg.jpg",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-09-03"),
  },
  {
    title: "Knife Set",
    price: 59.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/knife-set-yS7fJw5ilD9FMTQT4Gk3HlKBVD3m6Y.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-09-02"),
  },
  {
    title: "Cutting Board",
    price: 24.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/cutting-board-YROhMrfOmieSuIkYZuoG3S2leovayf.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-09-01"),
  },
  {
    title: "Microwave",
    price: 99.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/modern-microwave-oven-XafSbb8a2ibnyNoVhRZC0fDPQkpo15.png",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-31"),
  },
  {
    title: "Toaster",
    price: 34.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/toaster-VNFMTCna5zSa6SDmgQytLP6ml8yd1m.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-08-30"),
  },
  {
    title: "Kettle",
    price: 29.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/electric-kettle-fIq5HXwjrz6TkX5SH040d51e7KntOJ.png",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-29"),
  },
  {
    title: "Dish Set",
    price: 49.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/dish-set-efMZvCm21PpHXXJKATfzrJuYo6PgDL.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-28"),
  },
  {
    title: "Storage Containers",
    price: 39.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/storage-containers-ZaID6QrLug4FlyR6bc3B0nYFjK8j94.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-27"),
  },
  {
    title: "Vacuum Cleaner",
    price: 199.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/vacuum-cleaner-IKo5QHbtyX64j0TDE0dYJhohVUyPFv.jpg",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-08-26"),
  },
  {
    title: "Mop and Bucket",
    price: 34.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/mop-and-bucket-r3lHrcEWpIqfm75eFYqseLdbJdLZRE.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-08-25"),
  },
  {
    title: "Lamp",
    price: 44.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/mop-and-bucket-r3lHrcEWpIqfm75eFYqseLdbJdLZRE.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-24"),
  },
  {
    title: "Wall Clock",
    price: 24.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/modern-wall-clock-CFKjjDwR11Q6QfpkP8yegZatLDQyuo.png",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-08-23"),
  },
  {
    title: "Throw Pillow",
    price: 29.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/throw-pillow-qinXsUenOpylnYsRgT14LgLLvNXt18.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-22"),
  },
  {
    title: "Curtains",
    price: 59.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/curtains-2rb3BtpxXKy65nSmBQkjXwX8d2lyNC.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-21"),
  },
  {
    title: "Rug",
    price: 79.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/rug-5QZK6fVN4tD3y6qiqRqs0jBfZXSXry.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-20"),
  },
  {
    title: "Bookshelf",
    price: 99.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/bookshelf-4ztlDPHY4CHCdHqtMLfCzXRRaWLnEk.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-19"),
  },
  {
    title: "Coffee Table",
    price: 129.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/modern-coffee-table-tut4uunLJgGXj1ksl1I5pRWOf2J5jT.png",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-18"),
  },
  {
    title: "Dining Chair",
    price: 89.99,
    category: "Home & Kitchen",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/attachments/gen-images/public/products/dining-chair-HoibG8V8xSAP4uQRXZWQWEvO4PHzbF.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-17"),
  },

  // Beauty & Personal Care - 20 products
  {
    title: "Moisturizer",
    price: 34.99,
    category: "Beauty & Personal Care",
    image: "https://dr.rashel.in/cdn/shop/files/Hyaluronicacidmoisturizercream_1024x1024.jpg?v=1712218398",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-16"),
  },
  {
    title: "Sunscreen SPF 50",
    price: 24.99,
    category: "Beauty & Personal Care",
    image: "https://www.newu.in/cdn/shop/files/1_e220deed-7886-4b7f-ad8f-2fb41a469824_1024x1024.jpg?v=1737721311",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-08-15"),
  },
  {
    title: "Shampoo",
    price: 14.99,
    category: "Beauty & Personal Care",
    image: "https://www.thedravyastore.com/cdn/shop/files/8K2A8864-1-1-scaled_1024x1024.jpg?v=1719758325",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-14"),
  },
  {
    title: "Conditioner",
    price: 14.99,
    category: "Beauty & Personal Care",
    image: "https://heyumanos.com/cdn/shop/files/umanosConditionerBottleBox_1024x1024.jpg?v=1719353171",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-13"),
  },
  {
    title: "Face Mask",
    price: 19.99,
    category: "Beauty & Personal Care",
    image: "https://nirvanabeing.com/cdn/shop/products/blueleft_1024x1024.png?v=1699527428",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-12"),
  },
  {
    title: "Lipstick",
    price: 16.99,
    category: "Beauty & Personal Care",
    image: "https://www.lagirlusa.com/cdn/shop/products/GLC581_prod_img_1024x1024.jpg?v=1699773955",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-08-11"),
  },
  {
    title: "Foundation",
    price: 29.99,
    category: "Beauty & Personal Care",
    image: "https://www.facescanada.com/cdn/shop/products/UltimeProHDRunwayReadyFoundation_PDP_Ivory_1024x1024.jpg?v=1646397623",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-10"),
  },
  {
    title: "Eye Shadow Palette",
    price: 24.99,
    category: "Beauty & Personal Care",
    image: "https://hokmakeup.com/cdn/shop/files/G43312_prod_img_1024x1024_ab08b91c-7fd8-4b4b-9271-5253ce8d112e.jpg?v=1757405008",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-09"),
  },
  {
    title: "Mascara",
    price: 12.99,
    category: "Beauty & Personal Care",
    image: "https://swissbeauty.in/cdn/shop/files/Select_Game_Changer_Tubing_Mascara_1024x.jpg?v=1759300833",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-08"),
  },
  {
    title: "Perfume",
    price: 49.99,
    category: "Beauty & Personal Care",
    image: "https://www.lylablanc.in/cdn/shop/files/WhatsAppImage2025-06-26at3.45.22PM.jpg?v=1750932942",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-08-07"),
  },
  {
    title: "Body Lotion",
    price: 19.99,
    category: "Beauty & Personal Care",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMIvH9WskCdy_Ya96TJnv-SkhpCefGiYjzKA&s",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-06"),
  },
  {
    title: "Toothbrush",
    price: 9.99,
    category: "Beauty & Personal Care",
    image: "https://cdn-ilbepif.nitrocdn.com/pZrBMYQGrUZaHsbVKBUlrVMHXHFmMxDe/assets/images/optimized/rev-5919f9c/organicb.in/wp-content/uploads/2024/07/BrushYourWaytoaBrighterSmileandaGreenerPlanetYourGuidetoEco-FriendlyToothbrushes-1024x1024.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-08-05"),
  },
  {
    title: "Toothpaste",
    price: 7.99,
    category: "Beauty & Personal Care",
    image: "https://himalayawellness.in/cdn/shop/products/sparkling-white-toothpaste_1024x1024.jpg?v=1622095538",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-08-04"),
  },
  {
    title: "Deodorant",
    price: 8.99,
    category: "Beauty & Personal Care",
    image: "https://www.wildstone.in/cdn/shop/files/Edge150mlnew-Copy_1_1024x1024.jpg?v=1688560465",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-03"),
  },
  {
    title: "Hair Serum",
    price: 22.99,
    category: "Beauty & Personal Care",
    image: "https://trichocarepharma.com/wp-content/uploads/2024/07/Artboard-1-copy-6-1024x1024.webp",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-08-02"),
  },
  {
    title: "Face Cleanser",
    price: 16.99,
    category: "Beauty & Personal Care",
    image: "https://www.fixderma.com/cdn/shop/files/mandefix_foaming_face_wash_50ml.webp?v=1756383750",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-08-01"),
  },
  {
    title: "Exfoliator",
    price: 18.99,
    category: "Beauty & Personal Care",
    image: "https://mantleskin.com/cdn/shop/files/Mantle_TheEx_1024x1024.jpg?v=1754895116",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-31"),
  },
  {
    title: "Nail Polish",
    price: 9.99,
    category: "Beauty & Personal Care",
    image: "https://res.cloudinary.com/dtrouncfb/image/upload/c_crop,w_1024,h_1024/v1761152704/ed6a3eb3-94d0-4b58-bafa-44a422eb346e1718365080024ModelonesColoringLifeSoak-OffUVLEDCuredGelNailPolish7ml-MD-11_p0bsti.webp",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-30"),
  },
  {
    title: "Nail File Set",
    price: 12.99,
    category: "Beauty & Personal Care",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_n7dusMz72u1kF2exXNYWu2upchLKgPsKsg&s",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-07-29"),
  },
  {
    title: "Hair Brush",
    price: 14.99,
    category: "Beauty & Personal Care",
    image: "https://www.kareco.com/cdn/shop/products/BigHairBrushCollection_1024x1024.png?v=1659635651",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-28"),
  },

  // Sports & Fitness - 20 products
  {
    title: "Yoga Mat",
    price: 29.99,
    category: "Sports & Fitness",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhA60xCxttg3dtVwiuRJxk1psNe_p8QjZO4w&s",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-27"),
  },
  {
    title: "Dumbbells Set",
    price: 79.99,
    category: "Sports & Fitness",
    image: "https://samsfitness.com.au/wp-content/smush-webp/2020/09/CGHEXDB30KG-rubber-hex-dumbbell-pair-1024x1024.jpg.webp",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-07-26"),
  },
  {
    title: "Resistance Bands",
    price: 19.99,
    category: "Sports & Fitness",
    image: "https://slovicfitness.com/cdn/shop/files/Blue_1024x1024.jpg?v=1703061610",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-25"),
  },
  {
    title: "Jump Rope",
    price: 14.99,
    category: "Sports & Fitness",
    image: "https://www.bullrockfitness.com/wp-content/uploads/2024/12/1_Aluminium_Jump_Rope_self_Lock-1024x1024.jpg",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-24"),
  },
  {
    title: "Kettlebell",
    price: 34.99,
    category: "Sports & Fitness",
    image: "https://commercial.torquefitness.com/cdn/shop/files/2024_06_06-35LBRubberCoatedKettlebell-5832_1024x1024.jpg?v=1745251179",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-23"),
  },
  {
    title: "Pull-up Bar",
    price: 44.99,
    category: "Sports & Fitness",
    image: "https://www.bullrockfitness.com/wp-content/uploads/2023/04/rig_flying_pull_up_bar-1024x1024.jpg",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-22"),
  },
  {
    title: "Ab Roller",
    price: 24.99,
    category: "Sports & Fitness",
    image: "https://www.strengthshop.co.uk/cdn/shop/products/new-ab-wheel_1024x1024.jpg?v=1641970945",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-21"),
  },
  {
    title: "Foam Roller",
    price: 29.99,
    category: "Sports & Fitness",
    image: "https://worldfitness.com.au/cdn/shop/products/TriggerPointGRID2.0FoamRoller_1024x1024.png?v=1662693538",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-20"),
  },
  {
    title: "Gym Bag",
    price: 39.99,
    category: "Sports & Fitness",
    image: "https://fabrella.in/cdn/shop/files/m-iron-man-2020-monvelli-25-original-imag5dzanbyes3cw_1024x1024.jpg?v=1738867588",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-19"),
  },
  {
    title: "Water Bottle",
    price: 19.99,
    category: "Sports & Fitness",
    image: "https://www.milton.in/cdn/shop/files/Texture1024x1024.png?v=1735194226",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-18"),
  },
  {
    title: "Protein Shaker",
    price: 12.99,
    category: "Sports & Fitness",
    image: "https://zenithsports.in/cdn/shop/products/MainBanner.jpg?v=1632117877",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-17"),
  },
  {
    title: "Yoga Blocks",
    price: 16.99,
    category: "Sports & Fitness",
    image: "https://cdn.yanrefitness.com/cdn-cgi/imagedelivery/m94-xP3Y6Xwv_FOE9Rj47w/www.yanrefitness.com/2021/07/Figure-1-Cork-yoga-Blocks.jpg/w=1024",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-16"),
  },
  {
    title: "Yoga Strap",
    price: 12.99,
    category: "Sports & Fitness",
    image: "https://msfstore.fit/cdn/shop/files/Yoga_Strap_With_SS_Hook_A1_1_1024x1024.jpg?v=1740553059",
    rating: 4.3,
    reviews: [],
    createdAt: new Date("2025-07-15"),
  },
  {
    title: "Fitness Tracker",
    price: 99.99,
    category: "Sports & Fitness",
    image: "https://www.fabmart.com/cdn/shop/products/fitness-trackers-getactive-fitness-tracker-3_1024x1024.jpeg?v=1476774294",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-14"),
  },
  {
    title: "Skipping Rope",
    price: 16.99,
    category: "Sports & Fitness",
    image: "https://www.bullrockfitness.com/wp-content/uploads/2024/12/1_Aluminium_Jump_Rope_self_Lock-1024x1024.jpg",
    rating: 4.4,
    reviews: [],
    createdAt: new Date("2025-07-13"),
  },
  {
    title: "Punching Bag",
    price: 59.99,
    category: "Sports & Fitness",
    image: "https://m.media-amazon.com/images/I/81yKBX5LLZL._UF1000,1000_QL80_.jpg",
    rating: 4.7,
    reviews: [],
    createdAt: new Date("2025-07-12"),
  },
  {
    title: "Boxing Gloves",
    price: 44.99,
    category: "Sports & Fitness",
    image: "https://www.fightequipmentuk.com/cdn/shop/files/playerz-spartech-boxing-gloves-whiteblack-playerz-boxing.jpg?v=1743656385",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-11"),
  },
  {
    title: "Resistance Loop Bands",
    price: 14.99,
    category: "Sports & Fitness",
    image: "https://commercial.torquefitness.com/cdn/shop/products/LBT9_main_1024x1024.jpg?v=1670362452",
    rating: 4.6,
    reviews: [],
    createdAt: new Date("2025-07-10"),
  },
  {
    title: "Exercise Ball",
    price: 24.99,
    category: "Sports & Fitness",
    image: "https://www.msffit.com/cdn/shop/files/Anti-Burst_Exercise_Balls_1_1024x1024.jpg?v=1740565246",
    rating: 4.5,
    reviews: [],
    createdAt: new Date("2025-07-09"),
  },
  {
    title: "Massage Gun",
    price: 89.99,
    category: "Sports & Fitness",
    image: "https://healthsense.in/cdn/shop/files/Main_image_1024x1024.jpg?v=1719389910",
    rating: 4.8,
    reviews: [],
    createdAt: new Date("2025-07-08"),
  }]
export default products